set -g default-terminal "xterm-256color"
set -as terminal-overrides ",xterm-256color:Tc"
set -ga update-environment "COLORTERM"

set -g default-shell /home/linuxbrew/.linuxbrew/bin/bash
set -g prefix C-Space
bind C-Space send-prefix
set -g prefix2 C-b
bind C-b send-prefix -2
setw -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
set -g renumber-windows on
set -g allow-passthrough all
set -s set-clipboard on
set -g focus-events on

# New windows/splits inherit current pane's directory
# New windows always open in home directory
bind c new-window -c "~"

# Splits inherit current pane's directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Alt+hjkl to move between panes (no wrap)
bind -n M-h if -F '#{pane_at_left}' '' 'select-pane -L'
bind -n M-j if -F '#{pane_at_bottom}' '' 'select-pane -D'
bind -n M-k if -F '#{pane_at_top}' '' 'select-pane -U'
bind -n M-l if -F '#{pane_at_right}' '' 'select-pane -R'

# Alt+[] to move between windows
bind -n M-[ previous-window
bind -n M-] next-window

# Close pane without confirmation
bind-key x kill-pane

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @continuum-restore 'on'
set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-strategy-nvim 'session'

run '~/.tmux/plugins/tpm/tpm'
